[package]
name = "mytools"
version = "0.1.0"
authors = ["VictorBarbosa <victor.hugo.p.barbosa@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[dependencies]
clap="*"